In [1]:
%matplotlib inline
%load_ext autoreload
%autoreload 2

In [14]:
import os 
from pathlib import Path

import pandas as pd
from src.data.tsf_loader import convert_tsf_to_dataframe
DATA_DIR = Path(os.getcwd()).parent / "data"

pd.set_option("display.max_columns", None)
pd.set_option("display.max_colwidth", None)

## M4 Daily Dataset
Downloaded from [here](https://zenodo.org/records/4656548) courtesy of https://forecastingdata.org/

In [11]:
(df, frequency, forecast_horizon, contain_missing_values, contain_equal_length) = convert_tsf_to_dataframe(DATA_DIR / "m4_daily_dataset.tsf")

In [15]:
df.head()

,series_name,start_timestamp,series_value
0,T1,1994-01-03 12:00:00,"[1017.1, 1019.3, 1017.0, 1019.2, 1018.7, 1015.6, 1018.5, 1018.3, 1018.4, 1021.5, 1023.0, 1023.3, 1020.5, 1021.4, 1018.1, 1022.6, 1022.6, 1021.0, 1020.1, 1017.0, 1019.3, 1017.3, 1016.1, 1017.8, 1019.3, 1025.1, 1024.8, 1025.1, 1025.1, 1022.6, 1021.2, 1017.2, 1041.5, 1041.7, 1038.9, 1041.0, 1042.9, 1042.1, 1043.9, 1039.0, 1037.3, 1033.7, 1032.5, 1036.3, 1037.5, 1040.0, 1038.4, 1035.3, 1032.0, 1028.1, 1032.2, 1030.2, 1031.2, 1032.8, 1030.3, 1030.2, 1028.1, 1022.1, 1024.4, 1023.4, 1026.3, 1024.0, 1026.1, 1031.0, 1037.6, 1036.6, 1037.4, 1035.4, 1038.9, 1038.7, 1036.5, 1036.4, 1036.8, 1035.3, 1032.6, 1029.3, 1031.3, 1027.4, 1028.6, 1025.8, 1026.0, 1022.3, 1020.1, 1017.7, 1018.0, 1023.2, 1024.2, 1020.5, 1022.2, 1025.3, 1023.3, 1035.3, 1036.7, 1035.1, 1032.5, 1028.7, 1028.1, 1025.6, 1027.9, 1025.0, ...]"
1,T2,1995-01-02 12:00:00,"[2793.7, 2793.8, 2803.7, 2805.8, 2802.3, 2795.0, 2806.4, 2782.2, 2780.3, 2781.4, 2768.4, 2779.0, 2774.9, 2770.0, 2780.0, 2752.3, 2749.9, 2748.4, 2744.3, 2757.3, 2754.8, 2752.5, 2743.8, 2763.7, 2756.6, 2756.3, 2767.7, 2771.7, 2774.9, 2770.2, 2768.4, 2759.2, 2760.3, 2746.0, 2738.5, 2713.6, 2705.1, 2701.8, 2706.7, 2703.0, 2698.9, 2685.6, 2690.6, 2689.8, 2687.7, 2673.1, 2606.5, 2611.4, 2571.7, 2611.4, 2618.7, 2619.0, 2624.4, 2626.0, 2602.9, 2595.9, 2613.4, 2608.1, 2630.3, 2610.9, 2618.8, 2629.2, 2612.0, 2580.3, 2581.7, 2586.7, 2580.6, 2580.0, 2574.2, 2575.4, 2582.6, 2607.0, 2624.6, 2615.8, 2611.2, 2599.1, 2566.3, 2552.1, 2578.1, 2595.0, 2562.2, 2573.9, 2582.1, 2574.2, 2583.5, 2592.4, 2575.1, 2578.8, 2578.3, 2574.7, 2584.5, 2612.9, 2670.5, 2667.6, 2668.6, 2655.0, 2662.4, 2662.8, 2668.4, 2659.0, ...]"
2,T3,2006-01-05 12:00:00,"[1091.3, 1088.5, 1085.7, 1082.9, 1080.1, 1077.3, 1074.5, 1071.7, 1068.9, 1066.1, 1063.3, 1060.5, 1057.7, 1054.9, 1052.1, 1049.3, 1046.5, 1043.7, 1040.9, 1038.1, 1035.3, 1032.5, 1029.7, 1025.5, 1022.7, 1019.9, 1017.1, 1014.3, 1011.5, 1008.7, 1005.9, 1003.1, 1000.3, 997.5, 994.7, 991.9, 989.1, 986.3, 983.5, 980.7, 977.9, 975.1, 972.4, 969.5, 966.7, 963.9, 961.1, 958.3, 955.5, 952.7, 949.9, 947.1, 1119.3, 1117.9, 1115.1, 1112.3, 1109.5, 1106.7, 1103.9, 1101.1, 1098.3, 1095.5, 1092.7, 1089.9, 1087.1, 1084.3, 1081.5, 1078.7, 1075.9, 1073.1, 1070.3, 1067.5, 1064.7, 1061.9, 1059.1, 1056.3, 1053.5, 1050.7, 1047.9, 1045.2, 1042.3, 1039.5, 1036.7, 1033.9, 1031.1, 1028.3, 1025.5, 1022.7, 1019.9, 1017.1, 1014.3, 1011.5, 1008.7, 1005.9, 1003.1, 1000.3, 997.5, 994.7, 991.9, 989.1, ...]"
3,T4,1996-05-30 12:00:00,"[1092.0, 1078.0, 1064.0, 1050.0, 1036.0, 1022.0, 1008.0, 1092.0, 1078.0, 1064.0, 1050.0, 1036.0, 1022.0, 1092.0, 1079.0, 1064.0, 1050.0, 1036.0, 1022.0, 1092.0, 1078.0, 1064.0, 1092.0, 1078.0, 1065.0, 1092.0, 1078.0, 1064.0, 1050.0, 1036.0, 1022.0, 1092.0, 1078.0, 1064.0, 1050.0, 1092.0, 1078.0, 1064.0, 1050.0, 1092.0, 1078.0, 1065.0, 1050.0, 1036.0, 1093.0, 1078.0, 1064.0, 1050.0, 1092.0, 1078.0, 1064.0, 1050.0, 1092.0, 1078.0, 1064.0, 1050.0, 1036.0, 1092.0, 1078.0, 1176.0, 1148.0, 1120.0, 1092.0, 1064.0, 1036.0, 1009.0, 980.0, 952.0, 924.0, 896.0, 868.0, 840.0, 812.0, 784.0, 756.0, 729.0, 1246.0, 1218.0, 1190.0, 1162.0, 1134.0, 1106.0, 1078.0, 1050.0, 1022.0, 994.0, 966.0, 938.0, 910.0, 1064.0, 1036.0, 1008.0, 980.0, 952.0, 924.0, 896.0, 868.0, 840.0, 812.0, 784.0, ...]"
4,T5,1997-01-03 12:00:00,"[2938.63, 2956.44, 2964.41, 2972.41, 3014.97, 3014.23, 3024.08, 3031.97, 3062.7, 3057.19, 3063.93, 3068.45, 3072.98, 3431.69, 3436.86, 3441.45, 3446.05, 3454.46, 3459.42, 3463.44, 3467.3, 3485.64, 3475.19, 3478.89, 3482.34, 3486.01, 4087.11, 4092.18, 4096.39, 4100.62, 4106.51, 4111.35, 4115.66, 4119.77, 4139.93, 4130.28, 4135.06, 4139.71, 4145.03, 3920.15, 3990.62, 3993.84, 3520.12, 3538.05, 3525.42, 3528.37, 3530.95, 3554.46, 3543.37, 3547.85, 3551.94, 3555.81, 3946.24, 3950.03, 3954.77, 2682.61, 2740.91, 2740.91, 2740.91, 2740.91, 2793.43, 2793.43, 2793.43, 2793.43, 2793.43, 3460.19, 3927.06, 4363.58, 4366.82, 4397.12, 4405.22, 4408.33, 4411.21, 4436.47, 4444.49, 4447.26, 4450.29, 4453.69, 4618.39, 4624.01, 4627.16, 4630.32, 4663.52, 4672.88, 4676.28, 4679.36, 4682.69, 4720.34, 4724.02, 4727.64, 4731.26, 4883.14, 4890.45, 4897.19, 4903.86, 4962.9, 4974.44, 4979.23, 4982.22, 4987.42, ...]"